import { library } from '@fortawesome/fontawesome-svg-core';

import { faGoogle, faGithub, faTwitter } from '@fortawesome/free-brands-svg-icons';
import {
  faArrowRight,
  faBan,
  faBars,
  faBell,
  faCheckCircle,
  faCog,
  faEdit,
  faEllipsisV,
  faEnvelope,
  faExclamation,
  faExclamationCircle,
  faHistory,
  faHome,
  faInfoCircle,
  faKey,
  faLock,
  faPaperPlane,
  faPlus,
  faSignOutAlt,
  faSmile,
  faSpinner,
  faTag,
  faTimes,
  faUser,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faGoogle,
  faGithub,
  faTwitter,

  faEnvelope,
  faArrowRight,
  faEdit,
  faUser,
  faLock,
  faKey,
  faSpinner,
  faCheckCircle,
  faExclamationCircle,
  faInfoCircle,
  faSignOutAlt,
  faPaperPlane,
  faBars,
  faTimes,
  faHome,
  faBell,
  faPlus,
  faExclamation,
  faBan,
  faSmile,
  faEllipsisV,
  faCog,
  faTag,
  faHistory
);
